In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
plt.style.use("fivethirtyeight")

In [2]:
# gauss-jordan method
def gauss_jordan(a, b):
    n = len(b)
    
    # elimination phase
    #loops the row of the matrix
    for k in range(0, n - 1):
        #loops the values in the ith row (column values)
        for i in range(k+1, n):
            # Making the upper triangle, by altering some of the values in a for loop. the lower part will become 0.
            if a[i,k] != 0.0:
                lam  = a[i,k]/a[k,k]
                a[i,k+1:n] -= lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
    # back substitution
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - np.dot(a[k,k+1:n], b[k+1:n]))/a[k,k]
    return b

def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a

     
def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
        b[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [3]:
a = np.array([[3,-1],[2,1]], dtype = float)
b = np.array([[7],[8]], dtype = float)
x = gauss_jordan(a, b)
print(x)

[[3.]
 [2.]]


The Process of Gauss-Elimination
$
The matrix 
$

In [4]:
dim = int(input("Input how many dimensions"))
lhs = []
rhs = []
for i in range(dim):
    lhs.append([])
nums = int(input('How many values in a row'))
for k in range(dim):
    for j in range(nums):
        val = int(input('Input value'))
        lhs[k].append(val)
for l in range(dim):
    val = int(input('Input value'))
    rhs.append(val)
lhs_input = np.array(lhs,dtype= float)
rhs_input = np.array(rhs,dtype = float)
 

Input how many dimensions2
How many values in a row2
Input value3
Input value-1
Input value2
Input value1
Input value7
Input value8


###### 

In [5]:
lhs_input

array([[ 3., -1.],
       [ 2.,  1.]])

In [6]:
rhs_input

array([7., 8.])

In [7]:
gauss_jordan(lhs_input, rhs_input)

array([3., 2.])

In [8]:
dim = int(input("Input how many dimensions"))
lhs = np.array([])
rhs = np.array([])

# changing the dimensions of the matrix
np.reshape(lhs, dim)
np.reshape(rhs, dim)
nums = int(input('How many values in a row'))
for k in range(dim):
    for j in range(nums):
        val = int(input('Input value'))
        lhs[k].append(val)
for l in range(dim):
    val = int(input('Input value'))
    rhs.append(val)
lhs_input = np.array(lhs,dtype= float)
rhs_input = np.array(rhs,dtype = float)



Input how many dimensions2


ValueError: cannot reshape array of size 0 into shape (2,)

In [ ]:
A = LUdecomp(lhs_input)

In [ ]:
xDecomp = LUsolve(lhs_input,rhs_input)
print(xDecomp)

In [ ]:
# test equation
x1 = np.linspace(0, 10, 100)
y = lambda x : 3*x - 7
y2 = lambda x: 8 - 2*x

In [ ]:
# visual simulation
tick_spacing = 1
fig = plt.figure(1, figsize= (8,6)); plt.clf(); ax = fig.add_subplot(111)
ax.plot(x1, y(x1), label = "3x - y = 7")
ax.plot(x1, y2(x1), label = "2x + y = 8")
ax.plot(x, y(x), "o", markersize = 20)
ax.plot(x, y2(x), 's', markersize = 10)
ax.xaxis.set_major_locator(ticker.MultipleLocator(tick_spacing))
ax.yaxis.set_major_locator(ticker.MultipleLocator(2))
ax.set_title("Gauss-Jordan method")
ax.legend()

In [ ]:
fig1 = plt.figure(2, figsize = (8,6)); plt.clf()
ax1 = fig1.add_subplot(111)
ax1.plot(x1, y(x1))
ax1.plot(x1, y2(x1))
ax1.plot(xDecomp, y(xDecomp),'o', markersize = 20)
ax1.plot(xDecomp, y2(xDecomp), 's', markersize = 10)
ax1.set_title("LU decomposition")
ax1.xaxis.set_major_locator(ticker.MultipleLocator(tick_spacing))